name: push

on:
  push:
    branches: [ actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: setup
    #   run: |
    #     (apt-get update) \
    #     && (cmake --version || apt-get -y install cmake) \
    #     && (g++ --version || apt-get -y install g++) \
    #     && (git --version || apt-get -y install git)
    - name: build
      run: |
        mkdir -p build && cmake -S . -B build && cmake --build build
